#!/usr/bin/expect -f

# set variables
set idm_password $$IDM_PASS
spawn sudo tools/with_venv.sh bin/keystone-manage db_sync --populate

# Look for prompt
expect "Set a password for the idm user. (If you forget it, the password can be changed later using the admin token): "

# Send password aka $idm_password
send -- "$idm_password\r"

expect eof